### ISSUE TITLE
BUG - Scorecard GitHub action is failing

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1079]
**Describe the bug**

https://github.com/ossf/scorecard/runs/3734088142?check_suite_focus=true

**Comment by laurentsimon** [comment]
https://github.com/ossf/scorecard/runs/3734678406 is failing

**Comment by naveensrinivasan** [comment]
https://github.com/ossf/scorecard/runs/3749377785?check_suite_focus=true

**Comment by naveensrinivasan** [comment]
@laurentsimon it is failing

**Comment by laurentsimon** [comment]
I must have forgotten to push a new docker image. I pushed a new one.

**Comment by naveensrinivasan** [comment]
Still failing https://github.com/ossf/scorecard/runs/3750175726?check_suite_focus=true

**Comment by laurentsimon** [comment]
fixed https://github.com/ossf/scorecard/runs/3750344175?check_suite_focus=true
