### ISSUE TITLE
The "Token-Permissions" check seems to complain about codeql and labeler

### ISSUE THREAD

**Issue by evverx** [ossf/scorecard#1257]
Both `codeql` and `labeler` are widely used GH Actions that require non read-only tokens. The links to the "official" documentation where the permissions they have to have are mentioned:
https://github.com/github/codeql-action#usage
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input

```
./scorecard --verbosity Debug --checks Token-Permissions --show-details --format json  --repo=https://github.com/systemd/systemd | jq
...
      "details": [
        "Info: permissions set to 'read-all': .github/workflows/build_test.yml:1",
        "Debug: not a publishing workflow: .github/workflows/build_test.yml:1",
        "Debug: not a codeql workflow: .github/workflows/build_test.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/build_test.yml:1",
        "Debug: no permission defined: .github/workflows/build_test.yml:1",
        "Info: permissions set to 'read-all': .github/workflows/cifuzz.yml:1",
        "Debug: not a publishing workflow: .github/workflows/cifuzz.yml:1",
        "Debug: not a codeql workflow: .github/workflows/cifuzz.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/cifuzz.yml:1",
        "Debug: no permission defined: .github/workflows/cifuzz.yml:1",
        "Warn: no permission defined: .github/workflows/codeql-analysis.yml:1",
        "Debug: not a publishing workflow: .github/workflows/codeql-analysis.yml:1",
        "Debug: codeql workflow detected: .github/workflows/codeql-analysis.yml:1",
        "Info: 'actions' permission set to 'read': .github/workflows/codeql-analysis.yml:1",
        "Info: 'contents' permission set to 'read': .github/workflows/codeql-analysis.yml:1",
        "Debug: 'security-events' permission set to 'write': .github/workflows/codeql-analysis.yml:1",
        "Info: permissions set to 'read-all': .github/workflows/coverity.yml:1",
        "Debug: not a publishing workflow: .github/workflows/coverity.yml:1",
        "Debug: not a codeql workflow: .github/workflows/coverity.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/coverity.yml:1",
        "Debug: no permission defined: .github/workflows/coverity.yml:1",
        "Info: 'contents' permission set to 'read': .github/workflows/labeler.yml:1",
        "Debug: 'pull-requests' permission set to 'write': .github/workflows/labeler.yml:1",
        "Debug: not a publishing workflow: .github/workflows/labeler.yml:1",
        "Debug: not a codeql workflow: .github/workflows/labeler.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/labeler.yml:1",
        "Debug: no permission defined: .github/workflows/labeler.yml:1",
        "Info: permissions set to 'read-all': .github/workflows/linter.yml:1",
        "Debug: not a publishing workflow: .github/workflows/linter.yml:1",
        "Debug: not a codeql workflow: .github/workflows/linter.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/linter.yml:1",
        "Debug: no permission defined: .github/workflows/linter.yml:1",
        "Info: permissions set to 'read-all': .github/workflows/mkosi.yml:1",
        "Debug: not a publishing workflow: .github/workflows/mkosi.yml:1",
        "Debug: not a codeql workflow: .github/workflows/mkosi.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/mkosi.yml:1",
        "Debug: no permission defined: .github/workflows/mkosi.yml:1",
        "Info: permissions set to 'read-all': .github/workflows/unit_tests.yml:1",
        "Debug: not a publishing workflow: .github/workflows/unit_tests.yml:1",
        "Debug: not a codeql workflow: .github/workflows/unit_tests.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/unit_tests.yml:1",
        "Debug: no permission defined: .github/workflows/unit_tests.yml:1"
      "score": 0,
      "reason": "non read-only tokens detected in GitHub workflows",
      "name": "Token-Permissions",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/8da30e63afbc62e25c2c1252003aed9d34c3d04d/docs/checks.md#token-permissions",
        "short": "Determines if the project's workflows follow the principle of least privilege."
```

**Comment by evverx** [comment]
Apparently actually `scorecard` doesn't complain about `labeler` (even though I think it should because `scorecard` doesn't know what `labeler` is (as opposed to `codeql`) and the write permissions are explicitly specified there at the top level). I'll try to open another issue.

Regarding `codeql` I'm going to fix it with the following patch:
```diff
Author: Evgeny Vereshchagin <evvers@ya.ru>
Date:   Sun Nov 14 09:41:42 2021 +0000

    ci: tighten codeql and labeler even more

    by moving the read permissions to the top level and
    granting additional permissions to the specific jobs.
    It should help to prevent new jobs that could be added
    there eventually from having write access to resources they
    most likely would never need.

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
index c003cc5179..460002eaeb 100644
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -11,6 +11,9 @@ on:
   schedule:
     - cron: '0 1 * * *'

+permissions:
+  contents: read
+
 jobs:
   analyze:
     name: Analyze
@@ -20,7 +23,6 @@ jobs:
       cancel-in-progress: true
     permissions:
       actions: read
-      contents: read
       security-events: write

     strategy:
diff --git a/.github/workflows/labeler.yml b/.github/workflows/labeler.yml
index 800f8877a3..34d9d63d42 100644
--- a/.github/workflows/labeler.yml
+++ b/.github/workflows/labeler.yml
@@ -9,11 +9,12 @@ on:

 permissions:
   contents: read
-  pull-requests: write

 jobs:
   triage:
     runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
     steps:
     - uses: actions/labeler@69da01b8e0929f147b8943611bee75ee4175a49e
       with:
```

but I wouldn't expect everybody to change their actions (that most likely were borrowed from the official documentation) to please `scorecard`. I think `scorecard` should support permission granted to specific jobs without top level settings as well

**Comment by evverx** [comment]
Anyway, on an unrelated note, somehow `systemd` and a project maintained by exactly one person pushing commits directly to the master branch with no PRs, protected branches, reviews, tests and fuzz targets whatsoever keep receiving approximately the same "global" score from `scorecard` (probably due to inconclusive checks). I think I'm about to give up :-)

**Comment by laurentsimon** [comment]
Thanks for the report and the time you're investing in this. Don't give up, I'll help you out. Just tell me what you expect and I'll tell you why it's happening and we'll try to improve things, whether it's documentation, logging or result computation

**Comment by laurentsimon** [comment]
> Apparently actually `scorecard` doesn't complain about `labeler` (even though I think it should because `scorecard` doesn't know what `labeler` is (as opposed to `codeql`) and the write permissions are explicitly specified there at the top level). I'll try to open another issue.

is this related to https://github.com/ossf/scorecard/issues/1100?

> 
> Regarding `codeql` I'm going to fix it with the following patch:
> 
> ```diff
> Author: Evgeny Vereshchagin <evvers@ya.ru>
> Date:   Sun Nov 14 09:41:42 2021 +0000
> 
>     ci: tighten codeql and labeler even more
> 
>     by moving the read permissions to the top level and
>     granting additional permissions to the specific jobs.
>     It should help to prevent new jobs that could be added
>     there eventually from having write access to resources they
>     most likely would never need.
> 
> diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
> index c003cc5179..460002eaeb 100644
> --- a/.github/workflows/codeql-analysis.yml
> +++ b/.github/workflows/codeql-analysis.yml
> @@ -11,6 +11,9 @@ on:
>    schedule:
>      - cron: '0 1 * * *'
> 
> +permissions:
> +  contents: read
> +
>  jobs:
>    analyze:
>      name: Analyze
> @@ -20,7 +23,6 @@ jobs:
>        cancel-in-progress: true
>      permissions:
>        actions: read
> -      contents: read
>        security-events: write
> 
>      strategy:
> diff --git a/.github/workflows/labeler.yml b/.github/workflows/labeler.yml
> index 800f8877a3..34d9d63d42 100644
> --- a/.github/workflows/labeler.yml
> +++ b/.github/workflows/labeler.yml
> @@ -9,11 +9,12 @@ on:
> 
>  permissions:
>    contents: read
> -  pull-requests: write
> 
>  jobs:
>    triage:
>      runs-on: ubuntu-latest
> +    permissions:
> +      pull-requests: write
>      steps:
>      - uses: actions/labeler@69da01b8e0929f147b8943611bee75ee4175a49e
>        with:
> ```
> 
> but I wouldn't expect everybody to change their actions (that most likely were borrowed from the official documentation) to please `scorecard`. I think `scorecard` should support permission granted to specific jobs without top level settings as well

**Comment by evverx** [comment]
> is this related to #1100?

@laurentsimon I'm not sure it is. When I opened the issue the systemd project had
```
permissions:
  contents: read
  pull-requests: write
```
at the top level of the labeler action. `scorecard` said that
```
        "Info: 'contents' permission set to 'read': .github/workflows/labeler.yml:1",
        "Debug: 'pull-requests' permission set to 'write': .github/workflows/labeler.yml:1",
        "Debug: not a publishing workflow: .github/workflows/labeler.yml:1",
        "Debug: not a codeql workflow: .github/workflows/labeler.yml:1",
        "Debug: not a codeql upload SARIF workflow: .github/workflows/labeler.yml:1",
```
and didn't even warn that there was an action with write permissions.

**Comment by evverx** [comment]
The "codeql" part of this issue seems to be the same as #1100 though. Closing.

**Comment by laurentsimon** [comment]
> > is this related to #1100?
> 
> @laurentsimon I'm not sure it is. When I opened the issue the systemd project had

so I think it was: the workflow are not job-aware yet. Thanks for confirming.

> ```
> permissions:
>   contents: read
>   pull-requests: write
> ```
> 
> at the top level of the labeler action. `scorecard` said that
> 
> ```
>         "Info: 'contents' permission set to 'read': .github/workflows/labeler.yml:1",
>         "Debug: 'pull-requests' permission set to 'write': .github/workflows/labeler.yml:1",
>         "Debug: not a publishing workflow: .github/workflows/labeler.yml:1",
>         "Debug: not a codeql workflow: .github/workflows/labeler.yml:1",
>         "Debug: not a codeql upload SARIF workflow: .github/workflows/labeler.yml:1",
> ```
> 
> and didn't even warn that there was an action with write permissions.

Got it. It's listed as `Debug` instead of `Warn`. I will update to use `Warn` instead. Please let me know if there's something better we should do. Thanks!

**Comment by evverx** [comment]
> So we did not want to confuse developpers because it is not "fixable", i.e. the permission is needed to run the static analyzer.

@laurentsimon I agree `scorecard` shouldn't complain about `codeql` but those write permissions came from https://github.com/marketplace/actions/labeler (which apart from the write permissions uses `pull_request_target`). What I was trying to say is that I think by default write access should be at least suspicious if actions using them aren't well known like `codeql` or `labeler`.

I apologize for the confusion. I should have opened a separate issue about labeler.

**Comment by laurentsimon** [comment]
> > So we did not want to confuse developpers because it is not "fixable", i.e. the permission is needed to run the static analyzer.
> 
> @laurentsimon I agree `scorecard` shouldn't complain about `codeql` but those write permissions came from https://github.com/marketplace/actions/labeler (which apart from the write permissions uses `pull_request_target`). What I was trying to say is that I think by default write access should be at least suspicious if actions using them aren't well known like `codeql` or `labeler`.

Good point. We'd like to do that better. Today, we don't Warn if `contents:write` is used by a "known" release workflow, for example. But it's harder for us to do that for well-known actions because we don't know all of them: which d you think we should consider acceptable?

On a related note: we have a larger plan to cover dangerous workflows in https://github.com/ossf/scorecard/issues/426#issuecomment-856939499. We added the `pull_request_workflow` + `ref` part in this https://github.com/ossf/scorecard/commit/1050b1cd607b3686641c96ac071ae6774e60588f which was merged a few hours ago. You can test it out using `ENABLE_DANGEROUS_WORKFLOW=1` as env variable.

Please don't hesitate to add ideas to the tracking issue https://github.com/ossf/scorecard/issues/426#issuecomment-856939499. Suggestions and feedback are greatly appreciated.

> I apologize for the confusion. I should have opened a separate issue about labeler.

no worries.

**Comment by evverx** [comment]
>  it's harder for us to do that for well-known actions because we don't know all of them: which do you think we should consider acceptable?

I think by analogy with the list of well-know CI services in the CI-Test check new well-known actions could be added on a case-by-case basis. I haven't used any other actions with write permissions apart from `codeql` and `labeler` so I'd just add `labeler` to the list.

> We're hoping to leave this decision to users of scorecard, by providing our results in github.com/ossf/allstar a

The problem with this approach is that as far as I understand I could theoretically configure `scorecards` via `allstars` all I want locally but as we discussed elsewhere users would still open "issues" based on raw scorecard results that most likely wouldn't be based on any project-specific changes I made. I'd add that having looked at `allstars` and issues it has reported personally I wouldn't consider using it. It's just absolutely unwarranted bureaucracy with phrases like "achieve compliance" in the documentation. I understand where it's coming from and have no problem with it in certain places (usually far from GitHub) :-) I think I'll just keep extracting the results of "raw" scorecard checks I find useful and act on them.

> You can test it out using ENABLE_DANGEROUS_WORKFLOW=1 as env variable

I tried it out with the systemd repository and it failed with "internal error: invalid GitHub workflow" as far as I can see
```
  "date": "2021-11-15",
  "repo": {
    "name": "github.com/systemd/systemd",
    "commit": "947796eac385651f6a66fc0ce925a301b49f6fa4"
  },
  "score": -1.0,
  "checks": [
    {
      "details": null,
      "score": -1,
      "reason": "internal error: invalid GitHub workflow",
      "name": "Dangerous-Workflow",
...
    }
```

**Comment by laurentsimon** [comment]
> > it's harder for us to do that for well-known actions because we don't know all of them: which do you think we should consider acceptable?
> 
> I think by analogy with the list of well-know CI services in the CI-Test check new well-known actions could be added on a case-by-case basis. I haven't used any other actions with write permissions apart from `codeql` and `labeler` so I'd just add `labeler` to the list.

Thanks, we can do that. Can you create an issue for it? That should be pretty easy to implement.

> > We're hoping to leave this decision to users of scorecard, by providing our results in github.com/ossf/allstar a
> 
> The problem with this approach is that as far as I understand I could theoretically configure `scorecards` via `allstars` all I want locally but as we discussed elsewhere users would still open "issues" based on raw scorecard results that most likely wouldn't be based on any project-specific changes I made. 

what do you mean?

I'd add that having looked at `allstars` and issues it has reported personally I wouldn't consider using it. It's just absolutely unwarranted bureaucracy with phrases like "achieve compliance" in the documentation. 

It's more geared towards orgs that have many repos.

I understand where it's coming from and have no problem with it in certain places (usually far from GitHub) :-) I think I'll just keep extracting the results of "raw" scorecard checks I find useful and act on them.
> 
> > You can test it out using ENABLE_DANGEROUS_WORKFLOW=1 as env variable
> 
> I tried it out with the systemd repository and it failed with "internal error: invalid GitHub workflow" as far as I can see
> 
> ```
>   "date": "2021-11-15",
>   "repo": {
>     "name": "github.com/systemd/systemd",
>     "commit": "947796eac385651f6a66fc0ce925a301b49f6fa4"
>   },
>   "score": -1.0,
>   "checks": [
>     {
>       "details": null,
>       "score": -1,
>       "reason": "internal error: invalid GitHub workflow",
>       "name": "Dangerous-Workflow",
> ...
>     }
> ```

We're currently updating all our checks to using github.com/rhysd/actionlint, so I think we'll be able to fix this problem very soon. @asraa @chrismcgehee FYI

**Comment by asraa** [comment]
> I tried it out with the systemd repository and it failed with "internal error: invalid GitHub workflow" as far as I can see

I'll update the dangerous-workflow check with the workflow parser and make sure it passes this test. Thank you so much for pointing out these behaviors.

**Comment by evverx** [comment]
> what do you mean?

I think I need to reread the allstar documentation to be more specific. It could be I misunderstood how it's configured on top of scorecard, which it uses under the hood as far as I understand.

> in a couple weeks, we'll have a beta version of scorecard -as-GitHub-action

Looking at https://github.com/ossf/scorecard/issues/1074, it seems the action is supposed to send data to the "code-scanning" tab of repositories (by analogy with codeql I assume). I'm not sure I like this approach because it kind of makes it hard for external contributors who don't have access to that tab to be able to see issues to try to fix them. Basically, they have to fork repositories, wait for the cron job (or whatever else updates that tab) and keep track of those issues by constantly updating their forks. And they can't see issues marked as "false positives" in upstream projects for example so they might send PRs only to discover that they would be rejected.

**Comment by laurentsimon** [comment]
the action is aimed at repo owners, to help them run scorecard continuously without the pain of installing the tool. We'd like to extend it to be more usable for consumers... but for now we only support the BigQuery table. We have floated around the idea of REST API as well.

**Comment by evverx** [comment]
@laurentsimon I think issues actions like that report should be fixed eventually and it usually helps when more people have access to various dashboards. I'm not saying it's an issue related to the scorecard action specifically. It's just that that "code scanning" tab hides alerts from everybody apart from repo owners (which probably makes sense considering the nature of the tab) while at the same time all those alerts pop up on forks if they get updated more or less regularly so it isn't clear (to me at least) why that tab is hidden in the first place.

**Comment by josepalafox** [comment]
I will double check but I believe when you fork a repo it does keep the action configuration, but it has to be manually triggered, it doesn't run by default when the project is forked. This is in effect the fork-er re-running the scanner rather than the same scan results being replicated.  It wouldn't carry over suppressed alerts or the alert history with it either, I don't think. The small difference here is anyone could fork anything and run scorecard or any other SAST tool against it. I don't know if that helps the discussion but figured I'd just toss in a note for clarification.

**Comment by evverx** [comment]
> The small difference here is anyone could fork anything and run scorecard or any other SAST tool against it

And that's probably what motivated contributors would do. But I doubt "drive-by" contributors would want to go that far to just look at alerts they could potentially fix so they just go elsewhere.

FWIW judging by https://github.com/ossf/scorecard/issues/1074#issuecomment-933397297 the scorecard project has already run into something like that

**Comment by evverx** [comment]
Forgot to mention that also it doesn't seem to be possible to refer to those alerts in the commit messages because unlike, for example, links to OSS-Fuzz issues that are opened to the public eventually, all links to the security tab seem to always point to 404 for everybody except for repo owners.

**Comment by laurentsimon** [comment]
> @laurentsimon I think issues actions like that report should be fixed eventually and it usually helps when more people have access to various dashboards. I'm not saying it's an issue related to the scorecard action specifically. It's just that that "code scanning" tab hides alerts from everybody apart from repo owners (which probably makes sense considering the nature of the tab) while at the same time all those alerts pop up on forks if they get updated more or less regularly so it isn't clear (to me at least) why that tab is hidden in the first place.

I agree public dashboard would be a plus, this is an idea we've been tossing around. GitHub could have an option for devs to opt-in in order to share their dashboard, for example. Like you say, someone can run dependabot on a fork repo and dependenbot for security alerts. Doing this at scale for everyone is a little more challenging :-)

**Comment by laurentsimon** [comment]
> I will double check but I believe when you fork a repo it does keep the action configuration, but it has to be manually triggered, it doesn't run by default when the project is forked. This is in effect the fork-er re-running the scanner rather than the same scan results being replicated. It wouldn't carry over suppressed alerts or the alert history with it either, I don't think. The small difference here is anyone could fork anything and run scorecard or any other SAST tool against it. I don't know if that helps the discussion but figured I'd just toss in a note for clarification.

Thanks for the info @josepalafox !

**Comment by evverx** [comment]
> I will double check but I believe when you fork a repo it does keep the action configuration, but it has to be manually triggered, it doesn't run by default when the project is forked.

@josepalafox I might be wrong but looking at https://github.com/systemd/systemd/issues/21343 I think that's how Dependabot is supposed to work (in theory at least). GitHub Actions sending data to security scanning tabs are run automatically according to their configs.

**Comment by josepalafox** [comment]
I think the workflow you're looking for will be resolved in future updates to the platform and looks to be in beta now I believe: https://github.com/github/roadmap/issues/332

Re:dependabot I think runs differently because it is a vendored action.

**Comment by evverx** [comment]
> looking at systemd/systemd#21343 I think that's how Dependabot is supposed to work (in theory at least)

@laurentsimon FWIW I don't think scorecard should recommend using Dependabot until the issue mentioned at https://github.com/systemd/systemd/issues/21343 is fixed. Apparenlty it annoys people maintaining stable forks very much and they can't just remove and recreate those forks.

**Comment by evverx** [comment]
I've just opened https://github.com/ossf/scorecard/pull/1336 where I mentioned what Dependabot brings with it.

**Comment by evverx** [comment]
As far as I understand all "corner" cases should be addressed by config files by analogy with the binary-artifacts check: https://github.com/ossf/scorecard/issues/1256#issuecomment-1000091579. Closing this one.

**Comment by laurentsimon** [comment]
@evverx just be sure: is there still a problem with `labeler`? Anything we can to improve the results while w're working on the config files/policy?

**Comment by evverx** [comment]
Sorry. I wrote that comment semi-automatically. To judge from
```
        "Debug: run level 'pull-requests' permission set to 'write': .github/workflows/labeler.yml:17",
        "Info: top level 'contents' permission set to 'read': .github/workflows/linter.yml:14",
```
it should be fixed once https://github.com/ossf/scorecard/issues/1100 is closed. And when that happens as far as I understand it should be possible to use config files to prevent scorecard from complaining about it.

> Anything we can to to improve the results while we're working on the config files/policy?

I have to admit I'm not sure I like the idea of moving everything to config files because I think scorecard should be clever enough to handle most corner cases by default. But as far as I can tell "consumers" are willing to do that and as long as they don't try to push them upstream or ask maintainers to write those configs for them I think it should be fine. Just to clarify, I'm not saying there is anything wrong with config files. It's just that I don't think I'm a "consumer" in that particular sense.

**Comment by laurentsimon** [comment]
> Sorry. I wrote that comment semi-automatically. To judge from
> 
> ```
>         "Debug: run level 'pull-requests' permission set to 'write': .github/workflows/labeler.yml:17",
>         "Info: top level 'contents' permission set to 'read': .github/workflows/linter.yml:14",
> ```
> 
> it should be fixed once #1100 is closed. And when that happens as far as I understand it should be possible to use config files to prevent scorecard from complaining about it.

I actually think this issue has been addressed. The code now parses the GitHub action instead of using a simple regex.
The `Debug` message above does not reduce the score, it's only a debug message. The `Warn` messages indicates something that a user may address, but not debug messages. The reasoning is that we expect most users to not use the `verbosity Debug` flag.
We don't consider `pull-requests` as a permission of interest because it has many false positives, see https://github.com/ossf/scorecard/issues/1359. Ideally we should consider it of interest... Feel free to comment on the issue https://github.com/ossf/scorecard/issues/1359. This is something we may expose in raw results and let the policy decide whether it's OK...

> > Anything we can to to improve the results while we're working on the config files/policy?
> 
> I have to admit I'm not sure I like the idea of moving everything to config files because I think scorecard should be clever enough to handle most corner cases by default. But as far as I can tell "consumers" are willing to do that and as long as they don't try to push them upstream or ask maintainers to write those configs for them I think it should be fine. Just to clarify, I'm not saying there is anything wrong with config files. It's just that I don't think I'm a "consumer" in that particular sense.

just FYI, we'll be exposing a default policy file, which I think is where `scorecard should be clever enough to handle most corner cases by default` will be addressed. And we can refine this policy file given community feedback over time.

wdut?

**Comment by evverx** [comment]
> The Debug message above does not reduce the score, it's only a debug message. The Warn messages indicates something that a user may address, but not debug messages. The reasoning is that we expect most users to not use the verbosity Debug flag.

I think what I was trying to say is that `scorecard` should complain about it somehow to let people decided whether actions like that should be kept or not. Initially I singled out labeler because at the time "pull_request_target" was used there without any restrictions. Since I didn't think it was useful enough to warrant that I was going to throw it away but was outvoted :-) because it turns out those labels are actually used to categorize issues and so on. Eventually I added `pull-requests: write` there to limit the scope at least. Anyway, it seems this should be handled by the Dangerous workflow check probably and the token permission check works as expected.

> just FYI, we'll be exposing a default policy file, which I think is where scorecard should be clever enough to handle most corner cases by default will be addressed. And we can refine this policy file given community feedback over time.
> wdut?

It's better than just "raw" results but I'm not sure how those default policies would be shipped. If they aren't included in scorecard out of the box they should be kept somewhere and passed additionally to it and it makes it kind of hard to actually use them.

**Comment by laurentsimon** [comment]
> > The Debug message above does not reduce the score, it's only a debug message. The Warn messages indicates something that a user may address, but not debug messages. The reasoning is that we expect most users to not use the verbosity Debug flag.
> 
> I think what I was trying to say is that `scorecard` should complain about it somehow to let people decided whether actions like that should be kept or not. Initially I singled out labeler because at the time "pull_request_target" was used there without any restrictions. Since I didn't think it was useful enough to warrant that I was going to throw it away but was outvoted :-) because it turns out those labels are actually used to categorize issues and so on. Eventually I added `pull-requests: write` there to limit the scope at least. Anyway, it seems this should be handled by the Dangerous workflow check probably and the token permission check works as expected.
> 
> > just FYI, we'll be exposing a default policy file, which I think is where scorecard should be clever enough to handle most corner cases by default will be addressed. And we can refine this policy file given community feedback over time.
> > wdut?
> 
> It's better than just "raw" results but I'm not sure how those default policies would be shipped. If they aren't included in scorecard out of the box they should be kept somewhere and passed additionally to it and it makes it kind of hard to actually use them.

the default policy will be shipped within scorecard and used by default. Foe example `--policy default` or something along these lines.

**Comment by evverx** [comment]
> The raw results can be seen as an intermediate results for users to fiddle with, but we'll provide a default policy, like we do for scoring today. That's the current plan.

I think as long as the default policy is supposed to cover most corner cases it should be fine (and probably it doesn't even matter how it's implemented). It's just that I was initially under the impression that it was targeted at people somewhat specializing in writing those policies and personally I wouldn't want to do that because it would be one more thing to maintain and keep up to date.

**Comment by evverx** [comment]
FWIW @laurentsimon I think this issue can be closed. I'd go ahead and close it but since it was already reopened once I'm not sure if there is anything else that should be addressed here

**Comment by laurentsimon** [comment]
> > The raw results can be seen as an intermediate results for users to fiddle with, but we'll provide a default policy, like we do for scoring today. That's the current plan.
> 
> I think as long as the default policy is supposed to cover most corner cases it should be fine (and probably it doesn't even matter how it's implemented). It's just that I was initially under the impression that it was targeted at people somewhat specializing in writing those policies and personally I wouldn't want to do that because it would be one more thing to maintain and keep up to date.

it's just to allow use cases where users want a different policy from the default one. Today, the score is too coarse to allow for fine-grained policy, which is why we want to expose "raw" results. But we wont force users to write these policies, we'll have a default one.

**Comment by evverx** [comment]
> it's just to allow use cases where users want a different policy from the default one

The problem is that power users like that are usually best equipped to improve default policies. If it's much easier for them to keep their changes "downstream" they usually do just that. I mean, for example, it's hard to deal with selinux policies so people just have to report their issues upstream and the default policy gets better :-)

> But we wont force users to write these policies, we'll have a default one.

Good to know. Thanks!

**Comment by laurentsimon** [comment]
> > it's just to allow use cases where users want a different policy from the default one
> 
> The problem is that power users like that are usually best equipped to improve default policies. If it's much easier for them to keep their changes "downstream" they usually do just that. I mean, for example, it's hard to deal with selinux policies so people just have to report their issues upstream and the default policy gets better :-)

I agree we want power users to help us make the default policies better. But there are cases when different companies/teams view things differently about what's appropriate or not. Policies will allow them to do what they want.

> > But we wont force users to write these policies, we'll have a default one.
> 
> Good to know. Thanks!

**Comment by evverx** [comment]
> But there are cases when different companies/teams view things differently about what's appropriate or not. Policies will allow them to do what they want.

Can't argue with that but given that I've never seen anyone from those companies asking for anything here on GitHub publicly (or even discussing it) I can only speculate (while I'm pretty sure there are specific use cases that those policies should cater to). Anyway, not that it matters, but all things considered I agree that (unlike some decisions that I completely disagree with) those policies are useful. Thanks!
